// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static bool get isFirebaseConfiguredForCurrentPlatform {
    if (kIsWeb) {
      return web.appId.isNotEmpty && !web.appId.startsWith('REPLACE_WITH_');
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
      case TargetPlatform.iOS:
        return true;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return false;
      default:
        return false;
    }
  }

  static String get currentPlatformName {
    if (kIsWeb) {
      return 'web';
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return 'android';
      case TargetPlatform.iOS:
        return 'ios';
      case TargetPlatform.macOS:
        return 'macos';
      case TargetPlatform.windows:
        return 'windows';
      case TargetPlatform.linux:
        return 'linux';
      default:
        return 'unknown';
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration for hypnos-deamjournal
  // TODO: Replace 'REPLACE_WITH_WEB_APP_ID' with the actual appId.
  //       Obtain it from: Firebase Console → Project Settings → Your apps → Web app → App ID
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0_GKL2j4N3ztvu2gvGl9C80TZ4GWVjZo',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: '825550148513',
    projectId: 'hypnos-deamjournal',
    storageBucket: 'hypnos-deamjournal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYS3rrrT2AnWx8hKzUYVnBCzvEXgPJ8Ok',
    appId: '1:1021662923284:android:339712d76670fc2a007501',
    messagingSenderId: '1021662923284',
    projectId: 'hypnos-dream-journal',
    storageBucket: 'hypnos-dream-journal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz50whvs0gcYk1AtOrfSxrIw0WikhndB0',
    appId: '1:825550148513:ios:19a09e4151e7e5d021f1e0',
    messagingSenderId: '825550148513',
    projectId: 'hypnos-deamjournal',
    storageBucket: 'hypnos-deamjournal.firebasestorage.app',
    iosBundleId: 'com.example.hypnosDreamjournal',
  );
}
